# Generated by Django 4.1.7 on 2023-03-12 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_category_title_en_category_title_ky_extra_title_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='menu.category'),
        ),
        migrations.AlterField(
            model_name='food',
            name='extras',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='menu.extra'),
        ),
    ]
